name: Release Obsidian Plugin

on:
    push:
        tags:
            -   '*.*.*'

jobs:
    build-and-release:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                node-version: '22'
            - name: Install dependencies
              run: npm ci
            - name: Build the plugin
              run: npm run build
            - name: Release
              uses: softprops/action-gh-release@v2
              with:
                files: |
                  styles.css
                  manifest.json
                  dist/main.js
